// +build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_add(SB), $0-24

    MOVQ a+0(FP), DI
    MOVQ b+8(FP), SI

    WORD $0x048d; BYTE $0x37     // lea    eax, [rdi + rsi]
    MOVQ AX, c+16(FP)
    RET
